Update maven-tomcat.yml

diff --git a/.github/workflows/maven-tomcat.yml b/.github/workflows/maven-tomcat.yml
--- a/.github/workflows/maven-tomcat.yml
+++ b/.github/workflows/maven-tomcat.yml
@@ -22,6 +22,9 @@ jobs:
     - name: Build WAR
       run: mvn clean package
 
+    - name: Check if WAR exists
+      run: ls -lh target/*.war || echo "WAR not found!"
+
     - name: Deploy WAR to EC2
       uses: appleboy/scp-action@v0.1.7
       with:
@@ -29,5 +32,5 @@ jobs:
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_KEY }}
         port: 22
-        source: "target/webapp.war"
+        source: "target/webapp-1.0-SNAPSHOT.war"
         target: "/home/ubuntu/tomcat/webapps/"
